CREATE DATABASE afrifish;
USE afrifish;

-- Table des utilisateurs
CREATE TABLE utilisateur (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  telephone VARCHAR(50) NOT NULL,
  privilege ENUM ('admin','employer','fournisseur','gerant') NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  adresse VARCHAR(255) DEFAULT NULL,  
  ville VARCHAR(50) NOT NULL,  
  pays VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des entités 
CREATE TABLE entite (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reference VARCHAR(50) NOT NULL,
  codeEntite VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Table des affectations
CREATE TABLE affectation (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_entite INT DEFAULT NULL,
  id_utilisateur INT DEFAULT NULL,
  created_by INT DEFAULT NULL,
  modify_by INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_entite) REFERENCES entite(id) ON DELETE CASCADE,
  FOREIGN KEY (id_utilisateur) REFERENCES utilisateur(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des fournisseurs
CREATE TABLE fournisseur (
  id INT AUTO_INCREMENT PRIMARY KEY,
  raison_sociale VARCHAR(100) NOT NULL,
  representant VARCHAR(90) NOT NULL,
  telephone VARCHAR(50) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  pays VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des commandes
CREATE TABLE initCommande (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_entite INT NOT NULL,
  id_fournisseur INT NOT NULL,
  statut ENUM ('en cours','valider') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_entite) REFERENCES entite(id) ON DELETE CASCADE,
  FOREIGN KEY (id_fournisseur) REFERENCES fournisseur(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des règlements fournisseurs
CREATE TABLE reglementFourni (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_initCommande INT DEFAULT NULL,
  montant DECIMAL(15,2) NOT NULL CHECK (montant >= 0),
  modeRegler VARCHAR(250) DEFAULT NULL,
  statut INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_initCommande) REFERENCES initCommande(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des clients
CREATE TABLE client (
  id INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) DEFAULT NULL,  
  ville VARCHAR(50) NOT NULL,  
  pays VARCHAR(50) NOT NULL,
  telephone VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des ventes
CREATE TABLE initVente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_entite INT DEFAULT NULL,
  id_client INT DEFAULT NULL,
  statut ENUM ('en cours','valider') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_entite) REFERENCES entite(id) ON DELETE CASCADE,
  FOREIGN KEY (id_client) REFERENCES client(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des catégories d’articles
CREATE TABLE categorie (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_entite INT DEFAULT NULL,
  libelle VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_entite) REFERENCES entite(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des articles
CREATE TABLE article (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_categorie INT DEFAULT NULL,
  reference VARCHAR(75) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  puInitial DECIMAL(15,2) NOT NULL,
  qteInitiale DECIMAL(15,2) NOT NULL DEFAULT 0,
  pvInitial DECIMAL(15,2) NOT NULL,
  datePeremption DATE DEFAULT NULL,
  descriptions VARCHAR(250) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_categorie) REFERENCES categorie(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des paniers de commande
CREATE TABLE panierCommande (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_initCommande INT DEFAULT NULL,
  id_article INT DEFAULT NULL,
  quantite DECIMAL(15,2) NOT NULL CHECK (quantite > 0),
  statut ENUM ('en cours','terminer') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_initCommande) REFERENCES initCommande(id) ON DELETE CASCADE,
  FOREIGN KEY (id_article) REFERENCES article(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des paniers de vente
CREATE TABLE panierVente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_initVente INT DEFAULT NULL,
  id_article INT DEFAULT NULL,
  statut ENUM ('en cours','valider') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_initVente) REFERENCES initVente(id) ON DELETE CASCADE,
  FOREIGN KEY (id_article) REFERENCES article(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des factures
CREATE TABLE facture (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_initVente INT DEFAULT NULL,
  montant DECIMAL(15,2) NOT NULL,
  modePaiement ENUM('cash','virement','carte bancaire') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_initVente) REFERENCES initVente(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des opérations financières
CREATE TABLE typeOperation (
  id INT AUTO_INCREMENT PRIMARY KEY,
  libelle ENUM('Encaissement','Decaissement','Salaire'),
  nature ENUM('Entrer','Sortie'),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table des caisses
CREATE TABLE caisse (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_typeOperation INT DEFAULT NULL,
  montant DECIMAL(15,2) NOT NULL CHECK (montant >= 0),
  modeRegler VARCHAR(250) DEFAULT NULL,
  statut INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT DEFAULT NULL,
  modify_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  modify_by INT DEFAULT NULL,
  FOREIGN KEY (id_typeOperation) REFERENCES typeOperation(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

